### ISSUE TITLE
great work! code release as promised in the manuscript?

### ISSUE THREAD

**Issue by tom-rakesh** [JiayuYANG/Self-supervised-CVP-MVSNet#5]
Hi, this is really a great job. As promised to open source after acceptance, it's already 7 months past. 
I wish to know your code release schedule. 
Thanks.

**Comment by JiayuYANG** [comment]
Hi,

Sorry for the wait.
I just released the code for self-training.
The code for unsupervised initialization will be released shortly.

Cheers,
Jiayu.

**Comment by XYZ-qiyh** [comment]
Hello @JiayuYANG 
Thanks for your amazing work! I wonder about the timeline to release the unsupervised learning code.
Can't wait to train the network!
