### ISSUE TITLE
Question about the experimental setting about Self-sup. T&T benchmark

### ISSUE THREAD

**Issue by qiyh1037** [JiayuYANG/Self-supervised-CVP-MVSNet#9]
Hello, Dr. @JiayuYANG 
Thanks for your amazing work and releasing your code. 
I wonder the experimental setting about self-sup. on Tanks and Temples training set. The Table 4 in your paper indicated the model self-sup. trained on T&T training set achieved an excellent performance compared with the model on DTU dataset. However,  in your paper, there are no details about the experimental setting about the self-sup. on T&T training set.

The captured images of T&T benchmark contain more background regions compared with DTU dataset. But in the training stage, the model should focus on the foreground region, I guess. Is there any data pre-processing when self-sup. on T&T training set.

Looking forward to your reply.
Many thanks!

Below is one of the images of Ignatius and its ground-truth point cloud 👇
![000001](https://user-images.githubusercontent.com/37978171/149512757-016451e1-c70d-4d1e-935c-269dbe109f5c.jpg)

![snapshot09](https://user-images.githubusercontent.com/37978171/149512831-8d665abf-bd1b-4aee-a776-e433a1a2bf0d.png)

**Comment by Sun-Xinnnnn** [comment]
I found a dimension error after modifying the data set configuration code and path, so I would like to ask if you can send the test code of T&T to my email address? Thank you very much and look forward to your reply
